import ReduxProvider from './provider';
import type { Metadata } from 'next';
import { Providers } from './ThemProvider';
import { inter } from '@/fonts';
import './globals.css';

export const metadata: Metadata = {
  title: 'Home',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark:bg-black`}>
        <ReduxProvider>
          <Providers>{children}</Providers>
        </ReduxProvider>
      </body>
    </html>
  );
}
